#!/bin/bash
# script para a criacao de vhosts no padrao de instalacao aletta
# para o uso, digite ./criarvhost nomedovhost.org emailadmin@server.org
# 
# escrito por vitoriamario
# use este script como achar melhor. permitido a copia e modificacao

#verifica se o parametro nomedovhost foi digitado
if test $# = 0
then
	echo ERRO:: SINTAXE MAL FORMADA:
	echo Utilize ./criarvhost nomedovhost.org emailadmin@server.org
	exit 1
fi

# cria pastas htdocs
cd /var/controladorWeb/sitios
mkdir -p $1/htdocs-prod

#criacao de vhost
echo "
<VirtualHost *:80>
   ServerName $1
   ServerAlias www.$1
   ServerAdmin $2
   DocumentRoot /var/controladorWeb/sitios/$1/htdocs-prod
   ErrorLog /var/log/apache2/$1_error_log
   CustomLog /var/log/apache2/$1_access_log combined
   <Directory "/var/controladorWeb/sitios/$1/htdocs-prod">
         Options -Indexes FollowSymLinks MultiViews Includes
         AllowOverride All
         Order allow,deny
         Allow from all
   </Directory>
</VirtualHost>" > /etc/apache2/vhosts/$1.vhosts

#criacao dos arquivos de log
touch /var/log/apache2/$1_error_log
touch /var/log/apache2/$1_access_log


#criar index - 403 forbinden
echo "$1 <br> adm: $2" > /var/controladorWeb/sitios/$1/htdocs-prod/index.html

# modifica permissoes dos arquivos criados
chmod 755 /var/controladorWeb/sitios/$1/htdocs-prod -R
chown www-data.www-data /var/controladorWeb/sitios/$1/htdocs-prod -R

#reiniciar apache
apache2ctl restart

#voltar para o diretorio /var/controladorWeb/services
cd /var/controladorWeb/services

#criar conf do awstats
#/var/controladorWeb/services/criaAWstats.sh

#manda acessar
echo "acesse agora pelo seu browser favorito http://$1"

